### ISSUE TITLE
Implement or delete "convert to wav" feature

### ISSUE THREAD

**Issue by niccolopretto** [MTG/andalusian-corpus-notebooks#3]
This feature it was thought in order to convert the mp3 of Dunya in wav. This functionality was required in order to create a directory also usable in the Dunya Desktop (which require wav file). This feature is not necessary for notebooks. So it is necessary to evaluate if this feature is useful or not for future works.  

https://github.com/MTG/andalusian-corpus-notebooks/blob/c634b9aa44ff3da24c8e3115f5ea7fbddf4c7916/gui/gui_corpora.py#L203-L209

**Comment by miguelgcasado** [comment]
I think that, at the moment, we don't need  this conversion tool for any purpose, so it should probably be deleted. In case we need it in the future, wav-mp3 is easy to integrate, or it could be done in a separate script.

**Comment by niccolopretto** [comment]
It is ok. We can delete it.
